#!/bin/bash
# run_scan.sh — worker-node entry point for the pengy-equivalent reproduction DAG.
#
# One script, three phases (selected by the first argument), so the shared
# environment setup lives in a single place:
#
#   train   $1=BASE_TAG $2=TRAINFRAC
#           Train ONE IsolationForest on a fraction (TRAINFRAC) of good_list
#           (pinned config: good_run_list_TRAINING.txt, seed 42) and save it
#           under models/<BASE_TAG>_<suffix>/.  No apply/evaluate/report/plots.
#           Any pre-existing model dir for the tag is wiped first so a fresh
#           submission always retrains (rescue DAGs skip the node entirely).
#
#   apply   $1=BASE_TAG $2=RUN_GROUP   (RUN_GROUP = run numbers joined by '+')
#           For each run: extract THAT run's rows from pengy's frozen manifest
#           (seed42/frac40 TSV), apply the model to exactly those paths in a
#           node-local scratch dir, validate coverage, then atomically publish
#           <tag>_run<N>.csv (+ _paths.txt) to the EOS per-run dir.  This
#           mirrors pengy's run_apply_juan_reproduction_*_one_run.sh: no
#           re-sampling (his exact 40% subruns), no direct EOS appends (a
#           retried job re-publishes atomically instead of corrupting a
#           partial file).
#
#   combine $1=BASE_TAG
#           Merge all per-run CSVs into one log, wipe any stale eval outputs
#           (evaluate AUTO-SKIPS when eval_summary.txt exists), then evaluate →
#           report → plots.  Ground truth is the TEXT LIST (cfg good_list):
#           pipeline.py switches to catalogue GT only when --train-goodRunList
#           is passed, which is deliberately omitted here — catalogue-Tight
#           yields known_good = 0 on this run range and no FP rate at all.
#
# Submitted by submit_scan_{train,apply,combine}.sub, ordered by condor/scan.dag
# (train → apply → combine).  All parameter files are generated by batch_submit.sh.
#
# Tag handling (see src/pipeline.py): the train phase uses plain
# --good-list/--fraction, so no quality suffix is added; the feature flags
# below append _noTrigger_noLVDS_ignoreTriggerConfig.  Every phase passes the
# SAME flags so train/apply/combine all resolve the same model directory.

set -euo pipefail

# ── Constants shared by all phases ────────────────────────────────────────────
CONFIG="configs/repro_pengy_exact.yaml"      # pinned pengy params (z8, c0.001, 2/5/5/15, seed 42)
SCAN_SUBDIR="repro_pengy_dag"                # reports/<SUBDIR>, plots/<SUBDIR> (small, stay on AFS)
MANIFEST_REL="condor/apply_good_training_sampled_paths_seed42_frac40.tsv"

# Feature variant: digi only, no trigger config — pengy's juan_reproduction
# setup.  Every phase must pass the SAME flags: pipeline.py builds the
# model-tag suffix from the resolved feature flags, so a mismatch between train
# and apply would send apply looking for a model directory that was never
# written.
FEATURE_FLAGS=(--no-trigger --no-trigger-LVDS --no-trigger-config)
TAG_SUFFIX="_noTrigger_noLVDS_ignoreTriggerConfig"

INSTALLATION_PATH="/afs/cern.ch/user/l/lbailloe/private/autoDQM/isolation_forest"
# Bulk CSVs live on EOS, not AFS (quota).  Per-run files are published with an
# atomic rename, never appended to in place — the fuse-friendly pattern.
SCAN_LOGS_DIR="/eos/user/l/lbailloe/autoDQM_scan/logs/${SCAN_SUBDIR}"

PHASE=${1:?Usage: run_scan.sh <train|apply|combine> ...}
shift

cd "${INSTALLATION_PATH}"
MANIFEST="${INSTALLATION_PATH}/${MANIFEST_REL}"

# ── Make pip --user packages visible on worker nodes (see run_pipeline.sh) ────
PYVER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
export PYTHONUSERBASE="${HOME}/.local"
export PATH="${HOME}/.local/bin:${PATH}"
export PYTHONPATH="${HOME}/.local/lib/python${PYVER}/site-packages:${INSTALLATION_PATH}:${PYTHONPATH:-}"

python3 -c "import pandas, sklearn, numpy, scipy, watchdog" || {
    echo "ERROR: required packages not found." >&2
    echo "Run 'bash setup.sh' on lxplus before submitting condor jobs." >&2
    exit 1
}

[ -f "${MANIFEST}" ] || {
    echo "ERROR: frozen manifest not found: ${MANIFEST}" >&2
    echo "       git checkout origin/branch_peng -- ${MANIFEST_REL}" >&2
    exit 1
}

# EOS must be reachable and the scan output dir must exist before any phase
# writes to it; failing here (exit 1) is deliberate — it is a systemic
# problem, unlike a single run with missing data.
mkdir -p "${SCAN_LOGS_DIR}" || {
    echo "ERROR: cannot create scan logs dir on EOS: ${SCAN_LOGS_DIR}" >&2
    exit 1
}

echo "============================================================"
echo "  autoDQM pengy-equivalent repro — phase: $PHASE"
echo "  Host : $(hostname)"
echo "  Start: $(date -u)"
echo "============================================================"

case "$PHASE" in
    # ── Phase 1: train one model for one fraction ────────────────────────────
    train)
        BASE_TAG=${1:?Usage: run_scan.sh train <base_tag> <train_fraction>}
        TRAINFRAC=${2:?Usage: run_scan.sh train <base_tag> <train_fraction>}
        RESOLVED_TAG="${BASE_TAG}${TAG_SUFFIX}"
        echo "  Base tag   : $BASE_TAG   (model dir: models/${RESOLVED_TAG}/)"
        echo "  Train frac : $TRAINFRAC  (of good_list, seed 42)"
        echo ""
        # Fresh retrain: without this, step_train AUTO-SKIPS on an existing
        # model dir and the scan silently reuses a stale model.
        rm -rf "models/${RESOLVED_TAG}"
        python3 -m src.pipeline \
            --config "$CONFIG" \
            --model-tag "$BASE_TAG" \
            --fraction "$TRAINFRAC" \
            "${FEATURE_FLAGS[@]}" \
            --skip-apply --skip-evaluate --skip-report --skip-all-plots
        ;;

    # ── Phase 2: apply the model to each run's frozen manifest paths ─────────
    apply)
        BASE_TAG=${1:?Usage: run_scan.sh apply <base_tag> <run_group>}
        RUN_GROUP=${2:?Usage: run_scan.sh apply <base_tag> <run_group>}
        RESOLVED_TAG="${BASE_TAG}${TAG_SUFFIX}"
        IFS='+' read -ra RUNS <<< "$RUN_GROUP"
        echo "  Model tag  : ${RESOLVED_TAG}"
        echo "  Runs       : ${RUNS[*]}  (${#RUNS[@]} run(s), paths from frozen manifest)"
        echo ""
        PUBLISH_DIR="${SCAN_LOGS_DIR}/${RESOLVED_TAG}"   # combine expects <logs_dir>/<tag>/<tag>_run<N>.csv
        mkdir -p "${PUBLISH_DIR}"
        SCRATCH="${TMPDIR:-/tmp}/repro_pengy_apply_$$"
        trap 'rm -rf "${SCRATCH}"' EXIT
        n_ok=0
        n_fail=0
        for RUN in "${RUNS[@]}"; do
            echo "--- Run $RUN ---"
            RUN_TMP="${SCRATCH}/run_${RUN}"
            LOCAL_LOGS="${RUN_TMP}/logs"
            APPLY_LIST="${RUN_TMP}/apply_list.txt"
            mkdir -p "${LOCAL_LOGS}"
            # This run's frozen paths = manifest rows whose first column == RUN.
            awk -F'\t' -v r="$RUN" '$1 == r {print $2}' "${MANIFEST}" > "${APPLY_LIST}"
            N_EXPECTED=$(wc -l < "${APPLY_LIST}")
            if [ "$N_EXPECTED" -eq 0 ]; then
                echo "WARNING: run $RUN has no rows in the manifest — skipping" >&2
                n_fail=$((n_fail + 1))
                continue
            fi
            echo "  ${N_EXPECTED} frozen subrun path(s)"
            # Apply into the node-local scratch logs dir: step_apply appends to
            # its log, so it must never point at the published EOS file.
            if python3 -m src.pipeline \
                    --config "$CONFIG" \
                    --model-tag "$BASE_TAG" \
                    --skip-train \
                    --apply-list "${APPLY_LIST}" \
                    --skip-evaluate --skip-report --skip-all-plots \
                    "${FEATURE_FLAGS[@]}" \
                    --logs-dir "${LOCAL_LOGS}"; then
                LOCAL_CSV="${LOCAL_LOGS}/${RESOLVED_TAG}.csv"
                LOCAL_PATHS="${LOCAL_LOGS}/${RESOLVED_TAG}_paths.txt"
                # Coverage check: resolve_run_list silently drops paths missing
                # from EOS; an undersized log would skew the FP denominator.
                if python3 - "${LOCAL_CSV}" "${N_EXPECTED}" <<'EOF'
import sys, pandas as pd
csv_path, expected = sys.argv[1], int(sys.argv[2])
n = pd.read_csv(csv_path, usecols=["filename"], low_memory=False)["filename"].nunique()
if n != expected:
    raise SystemExit(f"ERROR: {n} unique subruns in log != {expected} manifest paths")
EOF
                then
                    # Atomic publish (same pattern as pengy's one-run script):
                    # copy to a temp name on EOS, then rename into place.
                    CSV_TMP="${PUBLISH_DIR}/.${RESOLVED_TAG}_run${RUN}.csv.tmp.$$"
                    cp -p "${LOCAL_CSV}" "${CSV_TMP}"
                    mv -f "${CSV_TMP}" "${PUBLISH_DIR}/${RESOLVED_TAG}_run${RUN}.csv"
                    if [ -s "${LOCAL_PATHS}" ]; then
                        PATHS_TMP="${PUBLISH_DIR}/.${RESOLVED_TAG}_run${RUN}_paths.txt.tmp.$$"
                        cp -p "${LOCAL_PATHS}" "${PATHS_TMP}"
                        mv -f "${PATHS_TMP}" "${PUBLISH_DIR}/${RESOLVED_TAG}_run${RUN}_paths.txt"
                    fi
                    echo "  Published ${RESOLVED_TAG}_run${RUN}.csv"
                    n_ok=$((n_ok + 1))
                else
                    echo "WARNING: run $RUN failed coverage check — not published" >&2
                    n_fail=$((n_fail + 1))
                fi
            else
                echo "WARNING: run $RUN apply failed (exit $?) — continuing" >&2
                n_fail=$((n_fail + 1))
            fi
            rm -rf "${RUN_TMP}"
        done
        echo ""
        echo "  Apply summary: OK=$n_ok  FAILED=$n_fail  of ${#RUNS[@]}"
        # Never exit non-zero for per-run failures: all apply jobs are procs of
        # ONE DAG node, and DAGMan fails the node — and aborts the whole DAG —
        # if ANY proc exits non-zero.  The combine phase's coverage report is
        # where missing runs become visible.
        ;;

    # ── Phase 3: combine per-run outputs, then evaluate/report/plots ─────────
    combine)
        BASE_TAG=${1:?Usage: run_scan.sh combine <base_tag>}
        RESOLVED_TAG="${BASE_TAG}${TAG_SUFFIX}"
        echo "  Model tag  : ${RESOLVED_TAG}"
        echo ""
        # Coverage report BEFORE combining: per-run CSVs present vs manifest runs.
        n_csvs=$(find "${SCAN_LOGS_DIR}/${RESOLVED_TAG}" -name "${RESOLVED_TAG}_run*.csv" 2>/dev/null | wc -l)
        n_runs=$(cut -f1 "${MANIFEST}" | sort -un | wc -l)
        echo "  Coverage   : ${n_csvs} per-run CSV(s) of ${n_runs} manifest run(s)"
        [ "$n_csvs" -gt 0 ] || { echo "ERROR: no per-run CSVs to combine." >&2; exit 1; }

        echo "  --- Pass 1: combine per-run outputs ---"
        python3 -m src.pipeline \
            --config    "$CONFIG" \
            --model-tag "$BASE_TAG" \
            --skip-train \
            "${FEATURE_FLAGS[@]}" \
            --logs-dir  "${SCAN_LOGS_DIR}" \
            --combine-specific-run-outputs '*'

        echo ""
        echo "  --- Pass 2: evaluate (report + plots) ---"
        # Stale eval outputs mask new results: step_evaluate AUTO-SKIPS when
        # eval_summary.txt already exists.  Wipe this tag's report dir first.
        rm -rf "reports/${SCAN_SUBDIR}/${RESOLVED_TAG}" "plots/${SCAN_SUBDIR}/${RESOLVED_TAG}"
        # Ground truth: TEXT LIST (cfg good_list) — --train-goodRunList is
        # deliberately NOT passed; it would switch evaluate to catalogue GT,
        # which has no known-good subruns in this run range (known_good = 0,
        # no FP rate).  Text-list mode makes the FP rate comparable with
        # pengy's 473/13432 = 3.5%.
        python3 -m src.pipeline \
            --config      "$CONFIG" \
            --model-tag   "$BASE_TAG" \
            --skip-train --skip-apply \
            "${FEATURE_FLAGS[@]}" \
            --logs-dir    "${SCAN_LOGS_DIR}" \
            --reports-dir "reports/${SCAN_SUBDIR}" \
            --plots-dir   "plots/${SCAN_SUBDIR}"
        ;;

    *)
        echo "ERROR: unknown phase '$PHASE' (expected train|apply|combine)" >&2
        exit 1
        ;;
esac

echo ""
echo "============================================================"
echo "  Done: phase $PHASE  $(date -u)"
echo "============================================================"
