#!/bin/bash
# run_scan.sh — worker-node entry point for the training-fraction scan.
#
# One script, three phases (selected by the first argument), so the shared
# environment setup lives in a single place:
#
#   train   $1=BASE_TAG $2=TRAINFRAC
#           Train ONE IsolationForest on the Tight good-run list at fraction
#           TRAINFRAC and save it under models/<BASE_TAG>_<QUALITY>/.
#           No apply/evaluate/report/plots.
#
#   apply   $1=BASE_TAG $2=RUN_GROUP   (RUN_GROUP = run numbers joined by '+')
#           Load the model <BASE_TAG>_<QUALITY> (--skip-train) and apply it to
#           every run in RUN_GROUP via --apply-specific-run, writing one
#           logs/<SCAN_SUBDIR>/<tag>_run<N>.csv per run.  The SAME model is used
#           for every run and every batch — nothing is retrained here.
#
#   combine $1=BASE_TAG
#           Merge all per-run CSVs for the model into one log, then evaluate →
#           report → plots for that model.
#
# Submitted by submit_scan_{train,apply,combine}.sub, ordered by condor/scan.dag
# (train → apply → combine).  All parameter files are generated by batch_submit.sh.
#
# Tag handling (see src/pipeline.py): pipeline.py appends "_<QUALITY>" to the tag
# only while training (not under --skip-train).  So the train phase is given the
# BASE_TAG and lets the pipeline append the suffix, whereas the apply/combine
# phases run under --skip-train and are given the already-suffixed tag
# "<BASE_TAG>_<QUALITY>" so they resolve to the exact same model directory.

set -euo pipefail

# ── Constants shared by all phases ────────────────────────────────────────────
CONFIG="configs/config.yaml"
QUALITY="Tight"                    # training/ground-truth quality level
SCAN_SUBDIR="scan_trainFracSweep"  # reports/<SUBDIR>, plots/<SUBDIR> (small, stay on AFS)
APPLY_FRAC="1.0"                   # --apply-specific-run-fraction (1.0 = all subruns)
INSTALLATION_PATH="/afs/cern.ch/user/l/lbailloe/private/autoDQM/isolation_forest"
# Bulk scan CSVs live on EOS, not AFS: per-run outputs are ~1 GB per fraction
# and the combine step writes an equal-sized merged log per fraction (~9 GB
# working set for 5 fractions) — more than any AFS home quota.  EOS is mounted
# on the batch workers, and these are large sequential writes (the
# fuse-friendly case).
SCAN_LOGS_DIR="/eos/user/l/lbailloe/autoDQM_scan/logs/${SCAN_SUBDIR}"

PHASE=${1:?Usage: run_scan.sh <train|apply|combine> ...}
shift

cd "${INSTALLATION_PATH}"

# ── Make pip --user packages visible on worker nodes (see run_pipeline.sh) ────
PYVER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
export PYTHONUSERBASE="${HOME}/.local"
export PATH="${HOME}/.local/bin:${PATH}"
export PYTHONPATH="${HOME}/.local/lib/python${PYVER}/site-packages:${INSTALLATION_PATH}:${PYTHONPATH:-}"

python3 -c "import pandas, sklearn, numpy, scipy, watchdog" || {
    echo "ERROR: required packages not found." >&2
    echo "Run 'bash setup.sh' on lxplus before submitting condor jobs." >&2
    exit 1
}

# EOS must be reachable and the scan output dir must exist before any phase
# writes to it; failing here (exit 1) is deliberate — it is a systemic
# problem, unlike a single run with missing data.
mkdir -p "${SCAN_LOGS_DIR}" || {
    echo "ERROR: cannot create scan logs dir on EOS: ${SCAN_LOGS_DIR}" >&2
    exit 1
}

echo "============================================================"
echo "  autoDQM scan — phase: $PHASE"
echo "  Host : $(hostname)"
echo "  Start: $(date -u)"
echo "============================================================"

case "$PHASE" in
    # ── Phase 1: train one model for one fraction ────────────────────────────
    train)
        BASE_TAG=${1:?Usage: run_scan.sh train <base_tag> <train_fraction>}
        TRAINFRAC=${2:?Usage: run_scan.sh train <base_tag> <train_fraction>}
        echo "  Base tag   : $BASE_TAG   (model dir: models/${BASE_TAG}_${QUALITY}/)"
        echo "  Train frac : $TRAINFRAC"
        echo ""
        python3 -m src.pipeline \
            --config "$CONFIG" \
            --model-tag "$BASE_TAG" \
            --train-goodRunList \
            --train-goodRunList-quality "$QUALITY" \
            --train-goodRunList-fraction "$TRAINFRAC" \
            --skip-apply --skip-evaluate --skip-report --skip-all-plots
        ;;

    # ── Phase 2: apply that model to a group of runs (no retraining) ─────────
    apply)
        BASE_TAG=${1:?Usage: run_scan.sh apply <base_tag> <run_group>}
        RUN_GROUP=${2:?Usage: run_scan.sh apply <base_tag> <run_group>}
        MODEL_TAG="${BASE_TAG}_${QUALITY}"          # already-suffixed (used under --skip-train)
        IFS='+' read -ra RUNS <<< "$RUN_GROUP"
        echo "  Model tag  : $MODEL_TAG"
        echo "  Runs       : ${RUNS[*]}  (${#RUNS[@]} run(s), apply-fraction ${APPLY_FRAC})"
        echo ""
        n_ok=0
        n_fail=0
        for RUN in "${RUNS[@]}"; do
            echo "--- Run $RUN ---"
            if python3 -m src.pipeline \
                    --config "$CONFIG" \
                    --model-tag "$MODEL_TAG" \
                    --train-goodRunList \
                    --train-goodRunList-quality "$QUALITY" \
                    --skip-train \
                    --apply-specific-run "$RUN" \
                    --apply-specific-run-fraction "$APPLY_FRAC" \
                    --logs-dir "${SCAN_LOGS_DIR}"; then
                n_ok=$((n_ok + 1))
            else
                echo "WARNING: run $RUN failed (exit $?) — continuing" >&2
                n_fail=$((n_fail + 1))
            fi
        done
        echo ""
        echo "  Apply summary: OK=$n_ok  FAILED=$n_fail  of ${#RUNS[@]}"
        # Never exit non-zero for per-run failures: all apply jobs are procs of
        # ONE DAG node, and DAGMan fails the node — and aborts the whole DAG —
        # if ANY proc exits non-zero.  A single run with no files on EOS (e.g.
        # run 1617) must not kill the scan; the combine phase merges whatever
        # CSVs exist.  Systemic problems are still caught: the dependency check
        # above exits 1 before this phase, and combine fails if no CSVs landed.
        ;;

    # ── Phase 3: combine per-run outputs, then evaluate/report/plots ─────────
    combine)
        BASE_TAG=${1:?Usage: run_scan.sh combine <base_tag>}
        MODEL_TAG="${BASE_TAG}_${QUALITY}"
        echo "  Model tag  : $MODEL_TAG"
        echo ""
        echo "  --- Pass 1: combine per-run outputs ---"
        python3 -m src.pipeline \
            --config "$CONFIG" \
            --model-tag "$MODEL_TAG" \
            --skip-train \
            --logs-dir "${SCAN_LOGS_DIR}" \
            --combine-specific-run-outputs '*'

        echo ""
        echo "  --- Pass 2: evaluate (report + plots) ---"
        python3 -m src.pipeline \
            --config "$CONFIG" \
            --model-tag "$MODEL_TAG" \
            --train-goodRunList \
            --train-goodRunList-quality "$QUALITY" \
            --skip-train --skip-apply \
            --logs-dir    "${SCAN_LOGS_DIR}" \
            --reports-dir "reports/${SCAN_SUBDIR}" \
            --plots-dir   "plots/${SCAN_SUBDIR}"
        ;;

    *)
        echo "ERROR: unknown phase '$PHASE' (expected train|apply|combine)" >&2
        exit 1
        ;;
esac

echo ""
echo "============================================================"
echo "  Done: phase $PHASE  $(date -u)"
echo "============================================================"
