base: config.yaml
model_tag: sweep__ifContamination_0p001__zThreshold_8sigma__nEst_200__maxSamp_4096

includeConfigInfo_Trigger: true
includeConfigInfo_DAQ: false

z_threshold:      8.0
if_contamination: 0.001
if_n_estimators:  200
if_max_samples:   4096
