base: config.yaml
model_tag: sweep__ifContamination_0p002__zThreshold_7sigma__nEst_300__maxSamp_256

includeConfigInfo_Trigger: true
includeConfigInfo_DAQ: false

z_threshold:      7.0
if_contamination: 0.002
if_n_estimators:  300
if_max_samples:   256
